-- SELECT a.CATEGORY, a.PRICE, PRODUCT_NAME
-- FROM FOOD_PRODUCT a 
-- inner join
-- (
--     SELECT CATEGORY, max(PRICE) as MAX_PRICE
--     FROM FOOD_PRODUCT
--     WHERE CATEGORY IN ( '과자', '국', '김치', '식용유')
--     GROUP BY CATEGORY
-- ) b
-- ON a.PRICE = b.MAX_PRICE
-- AND a.CATEGORY = b.CATEGORY
-- ORDER BY PRICE desc

SELECT CATEGORY, PRICE as MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
AND (CATEGORY, PRICE) IN (SELECT CATEGORY, MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY)
ORDER BY PRICE desc;