-- 코드를 입력하세요
SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO, (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE 
                 FROM REST_REVIEW
                 GROUP BY REST_ID) temp
WHERE REST_INFO.REST_ID = temp.REST_ID
AND ADDRESS like '서울%' 
ORDER BY SCORE desc, FAVORITES desc