SELECT 
TITLE, a.BOARD_ID, REPLY_ID, WRITER_ID,CONTENTS, TO_CHAR(a.CREATED_DATE, 'YYYY-MM-DD') as CREATED_DATE
FROM USED_GOODS_REPLY a
JOIN
(
    SELECT TITLE, BOARD_ID, CREATED_DATE
    FROM USED_GOODS_BOARD
    WHERE TO_CHAR(CREATED_DATE, 'yyyy-mm') = '2022-10'
) b
ON a.BOARD_ID = b.BOARD_ID
ORDER BY CREATED_DATE, TITLE
