SELECT b.FOOD_TYPE, REST_ID,  REST_NAME, b.FAVORITES
FROM REST_INFO a, (SELECT FOOD_TYPE, MAX(FAVORITES) as FAVORITES 
                   FROM REST_INFO
                   GROUP BY FOOD_TYPE) b
WHERE a.FAVORITES = b.FAVORITES
AND a.FOOD_TYPE = b.FOOD_TYPE
ORDER BY FOOD_TYPE desc, FAVORITES desc